/* ===========================================================================
   LUMEN Studio — Dados mockados das bibliotecas (aditivo, sem API externa).
   Templates, músicas e elementos decorativos para /modelos, /musicas, /elementos.
   =========================================================================== */
import type { TemplateModel, MusicTrack, DecorElement } from '@/types/library'

export const TEMPLATES: TemplateModel[] = [
  {
    id: 'tmpl-reels-gancho',
    name: 'Reels Gancho de 3 Segundos',
    category: 'Reels',
    duration: '30s',
    gradient: 'from-violet-600 via-fuchsia-600 to-cyan-500',
    icon: '🎬',
    editorRoute: '/gravadora',
    description: 'Estrutura de abertura explosiva com pergunta + transição rápida.',
  },
  {
    id: 'tmpl-reels-tutorial',
    name: 'Reels Tutorial Passo a Passo',
    category: 'Reels',
    duration: '45s',
    gradient: 'from-purple-600 via-indigo-600 to-blue-500',
    icon: '📚',
    editorRoute: '/gravadora',
    description: 'Ensine uma skill rápida em 3 etapas com legendas destacadas.',
  },
  {
    id: 'tmpl-reels-storytelling',
    name: 'Reels Storytelling Pessoal',
    category: 'Reels',
    duration: '60s',
    gradient: 'from-pink-600 via-rose-600 to-orange-500',
    icon: '✨',
    editorRoute: '/gravadora',
    description: 'Narrativa em arco: conflito, virada e chamada final.',
  },
  {
    id: 'tmpl-tiktok-trend',
    name: 'TikTok Trend Viral',
    category: 'TikTok',
    duration: '15s',
    gradient: 'from-cyan-500 via-teal-500 to-emerald-500',
    icon: '🔥',
    editorRoute: '/gravadora',
    description: 'Formato curto e repetitivo para trend de áudio.',
  },
  {
    id: 'tmpl-tiktok-duvida',
    name: 'TikTok Responde Dúvida',
    category: 'TikTok',
    duration: '40s',
    gradient: 'from-sky-500 via-blue-600 to-indigo-600',
    icon: '💬',
    editorRoute: '/gravadora',
    description: 'Pegue um comentário e responda com dica direta.',
  },
  {
    id: 'tmpl-youtube-intro',
    name: 'YouTube Intro Impactante',
    category: 'YouTube',
    duration: '10s',
    gradient: 'from-red-600 via-rose-600 to-pink-600',
    icon: '▶️',
    editorRoute: '/gravadora',
    description: 'Abertura de canal com logo animado e gancho.',
  },
  {
    id: 'tmpl-youtube-revisao',
    name: 'YouTube Revisão de Produto',
    category: 'YouTube',
    duration: '8min',
    gradient: 'from-amber-500 via-orange-600 to-red-600',
    icon: '⭐',
    editorRoute: '/gravadora',
    description: 'Review completo com prós, contras e veredito.',
  },
  {
    id: 'tmpl-story-prod',
    name: 'Story Bastidores de Produto',
    category: 'Stories',
    duration: '15s',
    gradient: 'from-emerald-500 via-green-600 to-teal-600',
    icon: '📦',
    editorRoute: '/criar-post',
    description: 'Mostre os bastidores de criação do seu produto.',
  },
  {
    id: 'tmpl-story-enquete',
    name: 'Story Enquete Interativa',
    category: 'Stories',
    duration: '10s',
    gradient: 'from-fuchsia-500 via-pink-600 to-rose-600',
    icon: '📊',
    editorRoute: '/criar-post',
    description: 'Engaje com enquetes e caixinhas de perguntas.',
  },
  {
    id: 'tmpl-carrossel-lista',
    name: 'Carrossel Lista de 5 Dicas',
    category: 'Carrossel',
    duration: '5 slides',
    gradient: 'from-violet-600 via-purple-600 to-indigo-600',
    icon: '🎠',
    editorRoute: '/carrossel',
    description: 'Liste 5 dicas acionáveis com capa e CTA final.',
  },
]

export const MUSIC_TRACKS: MusicTrack[] = [
  {
    id: 'm1',
    title: 'Neon Dreams',
    artist: 'Lumen Beats',
    album: 'Cyber Nights',
    duration: 128,
    genre: 'Lo-fi',
    bpm: 72,
    cover: 'https://img.usecurling.com/p/300/300?q=neon+dreams+purple',
    color: '#7C5CFC',
  },
  {
    id: 'm2',
    title: 'Midnight Study',
    artist: 'Aurora Sound',
    album: 'Lo-fi Sessions',
    duration: 145,
    genre: 'Lo-fi',
    bpm: 68,
    cover: 'https://img.usecurling.com/p/300/300?q=midnight+study',
    color: '#6A48E0',
  },
  {
    id: 'm3',
    title: 'Coffee & Rain',
    artist: 'Mellow Moods',
    album: 'Rainy Day',
    duration: 162,
    genre: 'Lo-fi',
    bpm: 75,
    cover: 'https://img.usecurling.com/p/300/300?q=coffee+rain+window',
    color: '#906BFC',
  },
  {
    id: 'm4',
    title: 'Epic Horizon',
    artist: 'Cinematic Forge',
    album: 'Trailers Vol. 2',
    duration: 210,
    genre: 'Cinematic',
    bpm: 90,
    cover: 'https://img.usecurling.com/p/300/300?q=epic+horizon+mountains',
    color: '#22D3EE',
  },
  {
    id: 'm5',
    title: 'Rise of Heroes',
    artist: 'Orchestral Waves',
    album: 'Hero Themes',
    duration: 188,
    genre: 'Cinematic',
    bpm: 95,
    cover: 'https://img.usecurling.com/p/300/300?q=heroes+rise+orchestra',
    color: '#0EA5E9',
  },
  {
    id: 'm6',
    title: 'Final Battle',
    artist: 'Score Lab',
    album: 'Epic Drums',
    duration: 240,
    genre: 'Cinematic',
    bpm: 120,
    cover: 'https://img.usecurling.com/p/300/300?q=battle+epic+drums',
    color: '#0284C7',
  },
  {
    id: 'm7',
    title: 'Pulse Drive',
    artist: 'Synthwave Co.',
    album: 'Electric Avenue',
    duration: 175,
    genre: 'Eletrônico',
    bpm: 128,
    cover: 'https://img.usecurling.com/p/300/300?q=pulse+drive+synthwave',
    color: '#A855F7',
  },
  {
    id: 'm8',
    title: 'Cyber City',
    artist: 'Neon Pulse',
    album: 'Future Beats',
    duration: 198,
    genre: 'Eletrônico',
    bpm: 130,
    cover: 'https://img.usecurling.com/p/300/300?q=cyber+city+neon',
    color: '#C026D3',
  },
  {
    id: 'm9',
    title: 'Electric Soul',
    artist: 'Voltage',
    album: 'Dance Floor',
    duration: 156,
    genre: 'Eletrônico',
    bpm: 124,
    cover: 'https://img.usecurling.com/p/300/300?q=electric+soul+dance',
    color: '#DB2777',
  },
  {
    id: 'm10',
    title: 'Sunshine Pop',
    artist: 'The Happy Ones',
    album: 'Summer Days',
    duration: 134,
    genre: 'Pop',
    bpm: 110,
    cover: 'https://img.usecurling.com/p/300/300?q=sunshine+pop+summer',
    color: '#F59E0B',
  },
  {
    id: 'm11',
    title: 'Bubblegum',
    artist: 'Sugar Rush',
    album: 'Sweet Tunes',
    duration: 142,
    genre: 'Pop',
    bpm: 115,
    cover: 'https://img.usecurling.com/p/300/300?q=bubblegum+pink+candy',
    color: '#EC4899',
  },
  {
    id: 'm12',
    title: 'Golden Hour',
    artist: 'Daylight',
    album: 'Warm Glow',
    duration: 168,
    genre: 'Pop',
    bpm: 100,
    cover: 'https://img.usecurling.com/p/300/300?q=golden+hour+sunset',
    color: '#EAB308',
  },
  {
    id: 'm13',
    title: 'Street Flow',
    artist: 'MC Vortex',
    album: 'Underground',
    duration: 152,
    genre: 'Hip-hop',
    bpm: 88,
    cover: 'https://img.usecurling.com/p/300/300?q=street+flow+hiphop',
    color: '#F97316',
  },
  {
    id: 'm14',
    title: 'Boom Bap Classic',
    artist: 'Beat Architect',
    album: 'Raw Cuts',
    duration: 164,
    genre: 'Hip-hop',
    bpm: 92,
    cover: 'https://img.usecurling.com/p/300/300?q=boom+bap+classic+vinyl',
    color: '#EA580C',
  },
  {
    id: 'm15',
    title: 'Trap Vibes',
    artist: '808 Lord',
    album: 'Bass Drops',
    duration: 138,
    genre: 'Hip-hop',
    bpm: 140,
    cover: 'https://img.usecurling.com/p/300/300?q=trap+vibes+bass',
    color: '#DC2626',
  },
  {
    id: 'm16',
    title: 'Ocean Calm',
    artist: 'Serene Waves',
    album: 'Deep Blue',
    duration: 280,
    genre: 'Ambiente',
    bpm: 60,
    cover: 'https://img.usecurling.com/p/300/300?q=ocean+calm+blue',
    color: '#0891B2',
  },
  {
    id: 'm17',
    title: 'Forest Whispers',
    artist: 'Nature Sounds',
    album: 'Wild Echoes',
    duration: 320,
    genre: 'Ambiente',
    bpm: 55,
    cover: 'https://img.usecurling.com/p/300/300?q=forest+whispers+green',
    color: '#059669',
  },
  {
    id: 'm18',
    title: 'Stargazing',
    artist: 'Cosmic Drift',
    album: 'Beyond',
    duration: 260,
    genre: 'Ambiente',
    bpm: 62,
    cover: 'https://img.usecurling.com/p/300/300?q=stargazing+night+sky',
    color: '#4F46E5',
  },
  {
    id: 'm19',
    title: 'Chillwave Sunset',
    artist: 'Retro Youth',
    album: 'Pastel Skies',
    duration: 184,
    genre: 'Lo-fi',
    bpm: 80,
    cover: 'https://img.usecurling.com/p/300/300?q=chillwave+sunset+pastel',
    color: '#8B5CF6',
  },
  {
    id: 'm20',
    title: 'Triumph Anthem',
    artist: 'Brass Kings',
    album: 'Victory',
    duration: 205,
    genre: 'Cinematic',
    bpm: 110,
    cover: 'https://img.usecurling.com/p/300/300?q=triumph+anthem+brass',
    color: '#D97706',
  },
]

const svgShape = (shape: string, color: string) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><${shape} fill="${color}" /></svg>`

export const DECOR_ELEMENTS: DecorElement[] = [
  // Formas
  {
    id: 'e1',
    name: 'Retângulo Sólido',
    category: 'Formas',
    render: 'svg',
    color: '#7C5CFC',
    svg: svgShape('rect width="90" height="90" x="5" y="5" rx="8"', '#7C5CFC'),
  },
  {
    id: 'e2',
    name: 'Círculo Cheio',
    category: 'Formas',
    render: 'svg',
    color: '#22D3EE',
    svg: svgShape('circle cx="50" cy="50" r="42"', '#22D3EE'),
  },
  {
    id: 'e3',
    name: 'Triângulo',
    category: 'Formas',
    render: 'svg',
    color: '#F59E0B',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="50,8 92,90 8,90" fill="#F59E0B"/></svg>',
  },
  {
    id: 'e4',
    name: 'Estrela',
    category: 'Formas',
    render: 'svg',
    color: '#EC4899',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="50,5 61,38 95,38 67,58 78,92 50,72 22,92 33,58 5,38 39,38" fill="#EC4899"/></svg>',
  },
  {
    id: 'e5',
    name: 'Losango',
    category: 'Formas',
    render: 'svg',
    color: '#10B981',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="50,5 95,50 50,95 5,50" fill="#10B981"/></svg>',
  },
  {
    id: 'e6',
    name: 'Linha Grossa',
    category: 'Formas',
    render: 'svg',
    color: '#A855F7',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="5" y="44" width="90" height="12" rx="6" fill="#A855F7"/></svg>',
  },
  // Ícones
  { id: 'e7', name: 'Coração', category: 'Ícones', render: 'emoji', emoji: '❤️', color: '#EF4444' },
  { id: 'e8', name: 'Fogo', category: 'Ícones', render: 'emoji', emoji: '🔥', color: '#F97316' },
  { id: 'e9', name: 'Brilho', category: 'Ícones', render: 'emoji', emoji: '✨', color: '#FBBF24' },
  {
    id: 'e10',
    name: 'Lâmpada',
    category: 'Ícones',
    render: 'emoji',
    emoji: '💡',
    color: '#FCD34D',
  },
  { id: 'e11', name: 'Alvo', category: 'Ícones', render: 'emoji', emoji: '🎯', color: '#EF4444' },
  { id: 'e12', name: 'Câmera', category: 'Ícones', render: 'emoji', emoji: '📸', color: '#8B5CF6' },
  {
    id: 'e13',
    name: 'Estrela',
    category: 'Ícones',
    render: 'emoji',
    emoji: '🌟',
    color: '#FBBF24',
  },
  {
    id: 'e14',
    name: 'Músculo',
    category: 'Ícones',
    render: 'emoji',
    emoji: '💪',
    color: '#F87171',
  },
  { id: 'e15', name: 'Festa', category: 'Ícones', render: 'emoji', emoji: '🎉', color: '#A855F7' },
  {
    id: 'e16',
    name: 'Foguete',
    category: 'Ícones',
    render: 'emoji',
    emoji: '🚀',
    color: '#3B82F6',
  },
  // Molduras
  {
    id: 'e17',
    name: 'Moldura Simples',
    category: 'Molduras',
    render: 'svg',
    color: '#7C5CFC',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="6" y="6" width="88" height="88" rx="4" fill="none" stroke="#7C5CFC" stroke-width="4"/></svg>',
  },
  {
    id: 'e18',
    name: 'Moldura Dupla',
    category: 'Molduras',
    render: 'svg',
    color: '#22D3EE',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="4" y="4" width="92" height="92" rx="4" fill="none" stroke="#22D3EE" stroke-width="3"/><rect x="12" y="12" width="76" height="76" rx="3" fill="none" stroke="#22D3EE" stroke-width="2"/></svg>',
  },
  {
    id: 'e19',
    name: 'Moldura Cantos',
    category: 'Molduras',
    render: 'svg',
    color: '#F59E0B',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M5,25 L5,5 L25,5 M75,5 L95,5 L95,25 M95,75 L95,95 L75,95 M25,95 L5,95 L5,75" fill="none" stroke="#F59E0B" stroke-width="4"/></svg>',
  },
  {
    id: 'e20',
    name: 'Moldura Floral',
    category: 'Molduras',
    render: 'svg',
    color: '#EC4899',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="8" y="8" width="84" height="84" rx="12" fill="none" stroke="#EC4899" stroke-width="3" stroke-dasharray="6,3"/></svg>',
  },
  // Efeitos
  {
    id: 'e21',
    name: 'Glow Violeta',
    category: 'Efeitos',
    render: 'svg',
    color: '#7C5CFC',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><radialGradient id="g1"><stop offset="0%" stop-color="#7C5CFC" stop-opacity="0.8"/><stop offset="100%" stop-color="#7C5CFC" stop-opacity="0"/></radialGradient></defs><circle cx="50" cy="50" r="50" fill="url(#g1)"/></svg>',
  },
  {
    id: 'e22',
    name: 'Glow Ciano',
    category: 'Efeitos',
    render: 'svg',
    color: '#22D3EE',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><radialGradient id="g2"><stop offset="0%" stop-color="#22D3EE" stop-opacity="0.8"/><stop offset="100%" stop-color="#22D3EE" stop-opacity="0"/></radialGradient></defs><circle cx="50" cy="50" r="50" fill="url(#g2)"/></svg>',
  },
  {
    id: 'e23',
    name: 'Fade Inferior',
    category: 'Efeitos',
    render: 'svg',
    color: '#000000',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><linearGradient id="g3" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#000" stop-opacity="0"/><stop offset="100%" stop-color="#000" stop-opacity="0.8"/></linearGradient></defs><rect width="100" height="100" fill="url(#g3)"/></svg>',
  },
  {
    id: 'e24',
    name: 'Granulado',
    category: 'Efeitos',
    render: 'svg',
    color: '#888888',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><filter id="n1"><feTurbulence baseFrequency="0.9" numOctaves="3"/></filter><rect width="100" height="100" fill="#888" filter="url(#n1)" opacity="0.5"/></svg>',
  },
  {
    id: 'e25',
    name: 'Vinco Vertical',
    category: 'Efeitos',
    render: 'svg',
    color: '#7C5CFC',
    svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><linearGradient id="g4" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stop-color="#7C5CFC" stop-opacity="0.4"/><stop offset="50%" stop-color="#7C5CFC" stop-opacity="0"/><stop offset="100%" stop-color="#7C5CFC" stop-opacity="0.4"/></linearGradient></defs><rect width="100" height="100" fill="url(#g4)"/></svg>',
  },
  // Tipografia
  {
    id: 'e26',
    name: 'Aspas Grandes',
    category: 'Tipografia',
    render: 'emoji',
    emoji: '“',
    color: '#7C5CFC',
  },
  {
    id: 'e27',
    name: 'Seta Direita',
    category: 'Tipografia',
    render: 'emoji',
    emoji: '→',
    color: '#22D3EE',
  },
  {
    id: 'e28',
    name: 'Cerquilha',
    category: 'Tipografia',
    render: 'emoji',
    emoji: '#',
    color: '#F59E0B',
  },
  {
    id: 'e29',
    name: 'Arroba',
    category: 'Tipografia',
    render: 'emoji',
    emoji: '@',
    color: '#EC4899',
  },
  {
    id: 'e30',
    name: 'Ponto de Exclamação',
    category: 'Tipografia',
    render: 'emoji',
    emoji: '!',
    color: '#EF4444',
  },
]

export const CAROUSEL_EMOJIS = ['❤️', '🔥', '✨', '💡', '🎯', '📸', '🌟', '💪', '🎉', '🚀']

export const CAROUSEL_FONTS = ['Inter', 'Anton', 'Montserrat', 'Caveat', 'Serif', 'Mono']

export const STATIC_FONTS = ['Inter', 'Serif', 'Mono']

export const STATIC_TEMPLATES = [
  {
    id: 'tpl-citacao',
    name: 'Citação',
    backgroundColor: '#14141C',
    backgroundType: 'gradient' as const,
    backgroundGradient: 'from-violet-950 via-slate-950 to-cyan-950',
    elements: [
      {
        id: 'te1',
        type: 'text' as const,
        content: '"A consistência vence o algoritmo."',
        x: 100,
        y: 380,
        width: 880,
        height: 200,
        color: '#FFFFFF',
        fontFamily: 'Serif',
        fontSize: 56,
        align: 'center' as const,
        bold: true,
      },
      {
        id: 'te2',
        type: 'text' as const,
        content: '— LUMEN Studio',
        x: 100,
        y: 620,
        width: 880,
        height: 60,
        color: '#22D3EE',
        fontFamily: 'Inter',
        fontSize: 28,
        align: 'center' as const,
      },
    ],
  },
  {
    id: 'tpl-promocao',
    name: 'Promoção',
    backgroundColor: '#0F0F1A',
    backgroundType: 'gradient' as const,
    backgroundGradient: 'from-fuchsia-700 via-purple-700 to-indigo-700',
    elements: [
      {
        id: 'te3',
        type: 'text' as const,
        content: 'OFERTA RELÂMPAGO',
        x: 100,
        y: 120,
        width: 880,
        height: 80,
        color: '#FBBF24',
        fontFamily: 'Anton',
        fontSize: 64,
        align: 'center' as const,
        bold: true,
      },
      {
        id: 'te4',
        type: 'text' as const,
        content: '50% OFF hoje',
        x: 100,
        y: 380,
        width: 880,
        height: 160,
        color: '#FFFFFF',
        fontFamily: 'Inter',
        fontSize: 96,
        align: 'center' as const,
        bold: true,
      },
      {
        id: 'te5',
        type: 'text' as const,
        content: 'Use: LUMEN50',
        x: 100,
        y: 640,
        width: 880,
        height: 50,
        color: '#0F0F1A',
        fontFamily: 'Mono',
        fontSize: 32,
        align: 'center' as const,
      },
    ],
  },
  {
    id: 'tpl-anuncio',
    name: 'Anúncio',
    backgroundColor: '#0B0B10',
    backgroundType: 'color' as const,
    elements: [
      {
        id: 'te6',
        type: 'text' as const,
        content: 'NOVO CURSO',
        x: 80,
        y: 100,
        width: 920,
        height: 60,
        color: '#7C5CFC',
        fontFamily: 'Inter',
        fontSize: 32,
        align: 'left' as const,
        bold: true,
      },
      {
        id: 'te7',
        type: 'text' as const,
        content: 'Edição de Vídeo\npara Criadores',
        x: 80,
        y: 320,
        width: 920,
        height: 220,
        color: '#FFFFFF',
        fontFamily: 'Anton',
        fontSize: 88,
        align: 'left' as const,
        bold: true,
      },
      {
        id: 'te8',
        type: 'shape' as const,
        content: '',
        x: 80,
        y: 820,
        width: 280,
        height: 70,
        color: '#22D3EE',
        shape: 'rectangle' as const,
      },
      {
        id: 'te9',
        type: 'text' as const,
        content: 'INSCREVER',
        x: 80,
        y: 836,
        width: 280,
        height: 40,
        color: '#0B0B10',
        fontFamily: 'Inter',
        fontSize: 28,
        align: 'center' as const,
        bold: true,
      },
    ],
  },
  {
    id: 'tpl-informativo',
    name: 'Informativo',
    backgroundColor: '#0B0B10',
    backgroundType: 'gradient' as const,
    backgroundGradient: 'from-slate-900 via-slate-800 to-slate-900',
    elements: [
      {
        id: 'te10',
        type: 'text' as const,
        content: '📊 MÉTRICAS DA SEMANA',
        x: 80,
        y: 80,
        width: 920,
        height: 50,
        color: '#22D3EE',
        fontFamily: 'Inter',
        fontSize: 28,
        align: 'left' as const,
        bold: true,
      },
      {
        id: 'te11',
        type: 'text' as const,
        content: '+42%',
        x: 80,
        y: 200,
        width: 920,
        height: 200,
        color: '#7C5CFC',
        fontFamily: 'Anton',
        fontSize: 160,
        align: 'left' as const,
        bold: true,
      },
      {
        id: 'te12',
        type: 'text' as const,
        content: 'de engajamento em Reels\ncomparado à semana passada.',
        x: 80,
        y: 440,
        width: 920,
        height: 120,
        color: '#FFFFFF',
        fontFamily: 'Inter',
        fontSize: 36,
        align: 'left' as const,
      },
      {
        id: 'te13',
        type: 'shape' as const,
        content: '',
        x: 80,
        y: 620,
        width: 920,
        height: 4,
        color: '#7C5CFC',
        shape: 'line' as const,
      },
    ],
  },
]
